apiVersion: apps/v1
kind: Deployment
metadata:
  name: manoit-nginx
spec:
  replicas: 5
  selector:
    matchLabels:
      run: manoit-nginx
  template:
    metadata:
      labels:
        run: manoit-nginx
    spec:
      containers:
      - image: nginx
        name: manoit-nginx
        ports:
        - containerPort: 80
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: manoit-nginx
  annotations:
    notifications.argoproj.io/subscribe.on-sync-succeeded.slack: pod-noit

